services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: stockms
      POSTGRES_PASSWORD: stockms
      POSTGRES_DB: stockms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"

volumes:
  postgres_data:
