# services:
#   db:
#     image: postgres:13
#     container_name: postgres_stockms
#     environment:
#       POSTGRES_USER: stockms
#       POSTGRES_PASSWORD: stockms
#       POSTGRES_DB: stockms
#     volumes:
#       - postgres_data_stockms:/var/lib/postgresql/data
#     ports:
#       - "5555:5432"

# volumes:
#   postgres_data_stockms:

version: '3.8'

services:
  redis:
    image: 'redis:latest'
    container_name: redis_container
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:

